# LDP-gem5 SE workloads
# name executable [arguments...]
graph_bfs_queue_ss workloads/bin/graph_aarch64_bfs_queue workloads/dataset/sx-superuser.edge 194100 1
graph_bfs_queue_cg10 workloads/bin/graph_aarch64_bfs_queue workloads/dataset/cage10.edge 11400 1
graph_mst_queue_ss workloads/bin/graph_aarch64_mst_queue workloads/dataset/sx-superuser.edge 194100 1
graph_mst_queue_cg10 workloads/bin/graph_aarch64_mst_queue workloads/dataset/cage10.edge 11400 1
graph_sssp_queue_ss workloads/bin/graph_aarch64_sssp_queue workloads/dataset/sx-superuser.edge 194100 1
graph_sssp_queue_cg10 workloads/bin/graph_aarch64_sssp_queue workloads/dataset/cage10.edge 11400 1
database_hj_m workloads/bin/mchashjoins --algo=NPO_st --r-size=1280000 --s-size=1280000
database_gb_m workloads/bin/mchashjoins --algo=Group_by --r-size=1280000 --s-size=1280000
network_ipv4_m workloads/bin/ipv4_arm64 100000
